version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_password
    networks:
      - adventum

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    networks:
      - adventum
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - mysql

networks:
  adventum:
    name: adventum

