version: '3.8'

services:
  matomo:
    image: matomo:latest
    container_name: matomo-container
    ports:
      - "3333:80"
    networks:
      - adventum
    environment:
      - MATOMO_DATABASE_HOST=mysql
      - MATOMO_DATABASE_PORT=3306

networks:
  adventum:
    external: true

